import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#0f1724', 
    paddingHorizontal: 10,
    paddingVertical: 80,
  },
  header: {
    width: '100%',
    paddingHorizontal: 16,
    paddingVertical: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: 'transparent',
  },
  headerTitle: {
    color: '#ffffff',
    fontSize: 18,
    fontWeight: '700',
  },
  headerButton: {
    backgroundColor: '#1f6feb',
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 10,
  },
  headerButtonText: {
    color: '#fff',
    fontWeight: '600',
  },
  flexCenter: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  canvasWrapper: {
    flex: 1,
    marginHorizontal: 12,
    marginBottom: 12,
    borderRadius: 16,
    overflow: 'hidden',
    backgroundColor: '#f6f8fb',
    elevation: 6,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.12,
    shadowRadius: 12,
  },
  canvasContainer: {
    flex: 1,
    backgroundColor: '#ffffff',
    padding: 12,
  },
  toolbar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 12,
    paddingHorizontal: 18,
    backgroundColor: 'transparent',
    borderTopWidth: 0,
  },
  button: {
    padding: 12,
    borderRadius: 12,
    backgroundColor: '#1f6feb',
    marginHorizontal: 6,
  },
  buttonText: {
    color: '#fff',
    fontWeight: '700',
  },
  strokePreviewContainer: {
    position: 'absolute',
    bottom: 90,
    right: 20,
    width: 120,
    height: 120,
    borderWidth: 0,
    backgroundColor: '#fff',
    borderRadius: 14,
    padding: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.18,
    shadowRadius: 18,
    elevation: 8,
  },

  toolbarFloating: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  toolbarInner: {
    flexDirection: 'row',
    backgroundColor: 'rgba(255,255,255,0.06)',
    padding: 8,
    borderRadius: 30,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.18,
    shadowRadius: 12,
    elevation: 10,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.06)',
  },
  toolbarButton: {
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 12,
    paddingVertical: 8,
    marginHorizontal: 6,
    borderRadius: 20,
  },
  toolbarButtonIcon: {
    fontSize: 18,
    marginBottom: 4,
  },
  toolbarLabel: {
    fontSize: 12,
    color: 'black',
    fontWeight: '600',
  },
  toolbarButtonPrimary: {
    backgroundColor: '#1f6feb',
  },
  toolbarButtonSecondary: {
    backgroundColor: '#f4f4f4',
    borderWidth: 0,
  },
  toolbarButtonDanger: {
    backgroundColor: '#ff5c5c',
  },
});
